middlewares:
  https-redirectscheme:
    redirectScheme:
      scheme: https
      permanent: true

  default-headers:
    headers:
      frameDeny: true
      browserXssFilter: true
      contentTypeNosniff: true
      forceSTSHeader: true
      stsIncludeSubdomains: true
      stsPreload: true
      stsSeconds: 15552000
      customFrameOptionsValue: SAMEORIGIN
      customRequestHeaders:
        X-Forwarded-Proto: https

  default-whitelist:
    ipWhiteList:
      sourceRange:
      - "{{ whitelist_source_range }}"

  secured:
    chain:
      middlewares:
      - default-whitelist
      - default-headers
