services:
  pihole:
    container_name: pihole
    hostname: "{{ hostname }}"
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    restart: always
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEBPASSWORD}
    networks:
      - traefik
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_URL}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.entrypoints=https"

networks:
  traefik:
    name: traefik_default
    external: true