- name: Set authorized key
  hosts: "*"
  become: true
  tasks:
    - authorized_key:
      user: {{ ansible_user }}
      state: present
      key: "{{ lookup('file', '/home/server/.ssh/id_ed25519.pub'}}"
