- name: Check if device needs to be reboot
  hosts: all
  tasks:
    - name: Check reboot file
      stat:
        path: /var/run/reboot-required
      register: p
    - debug:
        msg: "Reboot required"
      when: p.stat.exists