- name: Require password for sudo
  hosts: "ray.local"
  become: true
  tasks:
    - name: Require user password for sudo commands for sudoers
      community.general.sudoers:
        name: sudoers-require-password
        group: sudo
        commands: ALL
        nopassword: false