- name: Traefik docker compose deploy
  hosts: "*"
  become: true
  tasks:
    - name: Docker Folder exists
      file:
        path: "/srv/docker/traefik"
        state: directory
        owner: "root"
        group: "root"

    - name: Traefik docker compose file exists
      copy:
        src: traefik-compose.yml
        dest: "/srv/docker/traefik/docker-compose.yml"
        owner: root
        group: root
        mode: 0600

    - name: Set variable based on hostname
      set_fact:
        hostname: "{{ inventory_hostname_short }}"
    
    - debug:
        var: hostname

    - name: Traefik .env file exists
      template:
        src: traefik.env
        dest: "/srv/docker/traefik/.env"
        mode: 0600

    - name: Start Docker container
      community.docker.docker_compose_v2:
        project_src: /srv/docker/traefik
      register: output

    - name: Show results
      debug:
        var: output
